# Generated by Django 5.1.3 on 2024-11-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bngjobs',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hydjobs',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='punejobs',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
